# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            桂圆的blog 
tagline:          '桂圆的blog'
description:      '活着就是为了更好的生活'
url:              https://guiyuan.github.io

author:
  name:           'Guiyuan Ji'
  url:            https://guiyuan.github.io

paginate:         10

# Custom vars

github:
  repo:           https://github.com/guiyuan
