name: 永远都是起点 
description: This is a blog for guiyuan
meta_description: "This is a blog for guiyuan"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://guiyuan.name'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://guiyuan.name'
author:         'Guiyuan Ji'

